### ISSUE TITLE
Добавить баннер 'donate'

### ISSUE THREAD

**Issue by Millon15** [unitfactoryAlumni/cheatera.pp.ua#100]
| Вопрос | Ответ |
| ------------ | ------------ |
| Что нужно добавить? | Собственно баннер 'donate' |
| Как это должно работать? | Человек нажимает на кнопку 'donate' и попадает на сторонний сервис(или нет?), где может задонатить нам(разрабам) на сервера etc.. |
| Как это не должно работать | Не должно не быть кнопки 'donate' |
| Какую проблему поможет решить эта фича? | Финансовую |

**Comment by setnemo** [comment]
можно добавить ссылки donate на моно, и ссылку открыть карту на моно. 
https://monobank.com.ua/r/ffYN - открыть карту моно (+50грн мне, +50грн открывшему карту)
https://send.monobank.com.ua/GRvvKkvg - перевод на карту моно

Для справки - за все время, что ссылка висела на старых читерах - перекинули 200грн) Сервер я оплатил на год за 300грн грубо (самый дешманский и тд)

На норм сервер я планирую выделить 80 баксов год. Через пару месяцев думаю
