### ISSUE TITLE
Добавить камеры с marvin.unit.ua

### ISSUE THREAD

**Issue by Millon15** [unitfactoryAlumni/cheatera.pp.ua#102]
| Вопрос | Ответ |
| ------------ | ------------ |
| Что нужно добавить? | Собсно требуется скомуниздить картинки с сайта(https://marvin.unit.ua/cams), которые обновляются с камер в юните,  |
| Как это должно работать? | Человек, находящийся в локальной сети юнита, заходит на наш сайт, мы делаем запросы по скомунизженным адресам, добавляем эти картинки к нам БД -- они становятся доступны всем, профит. |
| Как это не должно работать | Нас не должен спалить бокал и поменять эти адреса... |
| Какую проблему поможет решить эта фича? | Проблему черезмерной закрытости нашего сообщества |

P. S. Можно не комуниздить картинки в БД, так как это, по сути, никому не нужно.

**Comment by setnemo** [comment]
есть пара идей. Расскажу потом. Те ребята с е3 обзавидуются :1st_place_medal:
