### ISSUE TITLE
BUG: Incorrect status of searching a group

### ISSUE THREAD

**Issue by dlenskyi** [unitfactoryAlumni/cheatera.pp.ua#118]
| Вопрос | Ответ |
| ------------ | ------------ |
| OS | MacOS |
| Browser | Chrome |
| Theme | White |
| У вас получилось повторить баг? | да |

В списке тех, кто ищет группу на проект, допустим, Корвара, или тех, у кого validated is None, данный проект в интре как раз завалидирован

**Comment by setnemo** [comment]
приведи, пожалуйста, пример. Возможно человек сдал корвар, а потом нажал ретрай?

**Comment by dlenskyi** [comment]
В интре не отображается, нажал ли человек ретрай на Корваре. Но даже если бы и нажал, Корвар то у человека должен отображаться как Validated. Пример: профиль ypikul. 
Он его завалидировал, но в читерах отображается что нет

**Comment by setnemo** [comment]
Ага, у пикуля. Это все данные с апи. Он зарегался заново на проект судя по всему, и это создало запись. (по нему тре записи, одна 125, вторая и третья поиск группы - он два раза отрег). Пока что удаления объектов нет, но скоро будет
