### ISSUE TITLE
FEATURE: сделать переход teamplate c basic на advanced

### ISSUE THREAD

**Issue by zavrazhyn-artem** [unitfactoryAlumni/cheatera.pp.ua#128]
| Вопрос | Ответ |
| ------------ | ------------ |
| Что нужно добавить? | сделать переход teamplate c basic на advanced |
| Как это должно работать? | структура проекта должна полностью измениться, должны появиться новые приложения [backend => admin panel, console =>for scripts] |
| Как это не должно работать | новая структура проекта не должна быть трудно поддерживаемой |
| Какую проблему поможет решить эта фича? | облегчение дальнейшей поддержки кода и упрощение расширения функционала проекта |

**Comment by setnemo** [comment]
На данный момент сайт это просто вьюха для показа данных из БД. Архитектруно неверно менять и делать такой переход без изменения наполнения самой базы данными. По сути сайт просто это фронт-енд часть, а бек-енд у нас на питоне.В рамках опенсорс  части проекта это не будет меняться
