### ISSUE TITLE
#66 fix

### ISSUE THREAD

**Issue by Millon15** [unitfactoryAlumni/cheatera.pp.ua#129]

**Comment by setnemo** [comment]
@Millon15  сам пофикси, сам сделай ревью, сам проведи тесты. У меня тяжелая неделя(

**Comment by Millon15** [comment]
Исправлено

**Comment by setnemo** [comment]
Нужно еще добавить обновление времени из методов, которые используются для amount time at cluster в профиле @Millon15

**Comment by Millon15** [comment]
Done with #134
