### ISSUE TITLE
BUG: перестал обновлять уже 5 дней как мои (eamielin) данные из интры (левел, время в кластере пишет 0, корекшн поинты)(и не только мои)

### ISSUE THREAD

**Issue by ed-amielin** [unitfactoryAlumni/cheatera.pp.ua#133]
| cheatera перестал обновлять уже 5 дней как мои данные (eamielin) из интры (левел, время в кластере пишет вообще 0)(и не только мои) |
| ------------ | ------------ |
| OS | MacOS |
| Browser | Safari |
| Theme | Both |
| У вас получилось повторить баг? | да |

Шаги для повторения бага
1. Захожу на cheatera.pp.ua (хоть из дому хоть из кластера)
2. Логинюсь под собой (eamielin) посредством "with 42"
3. Выбираю пункт меню Students -> Members, перехожу
4. Фильтрую по году и месяцу (2018, setpember)
5. Наблюдаю баг - в моей строчке (eamielin) - уровень не соответствует интровскому уже 5 день, а время в кластере вообще пишет 0, конекшн поинты тоже не соответствуют уже 5 день.

**Comment by Millon15** [comment]
Исправлено

**Comment by setnemo** [comment]
@Millon15 проверял?

**Comment by Millon15** [comment]
@omentes Да, я вчера поправил базу, твои скрипты до сегодня всех юзеров успешно обновили.
