### ISSUE TITLE
BUG: 42 API Error

### ISSUE THREAD

**Issue by quentinleon** [unitfactoryAlumni/cheatera.pp.ua#135]
42 API error. Site unusable.

**Comment by setnemo** [comment]
@qwolf1999 
Please give more information

| Question | Answer |
| ------------ | ------------ |
| OS | MacOS |
| Browser | Safari |
| Theme | Dark / White / Both |
| Did you manage to repeat the bug? | yes |

Steps to repeat the bug
1. Open
2. Click
3. Select
4. Watch
5. Before you bug

**Comment by setnemo** [comment]
@Millon15 
`~/cheatera.pp.ua(master) » grep -rnw '42API'                                                                                                             omentes@manjaro
\common/messages/ru/app.php:161:    '42API error! Please, try again' => 'Ошибка 42АПИ. Попробуйте еще раз!',
helpers/Auth42.php:131:            throw new \yii\web\ForbiddenHttpException(Yii::t('app', '42API error! Please, try again'));
`

**Comment by quentinleon** [comment]
Seems to be a global problem regardless of platform. Looks like you were
able to recreate it.

**Comment by Millon15** [comment]
@ qwolf1999 No we cannot. Can you repeat it and send us a screenshot at least?

**Comment by quentinleon** [comment]
After logging in using 42 intra, all pages return "Error (#8) An internal server error occurred."
I am on Mac OS 10.13.3, using Chrome. Bug is repeatable.

**Comment by smonroe4242** [comment]
I'm having the same error. MacOS, Safari, default themes, and it repeats on literally every page I've tried.

**Comment by setnemo** [comment]
@smonroe4242 @qwolf1999 Thanks for the information, I can check it (I have job and little time for open source)

**Comment by setnemo** [comment]
@smonroe4242 @qwolf1999 

The error occurs when trying to authorize it in Intra (intra return bad responce). 

Are you all right with access to Intra?

**Comment by smonroe4242** [comment]
Intra access is fine, it appeard to have authorized me properly, but all
links i followed after that gave error

**Comment by setnemo** [comment]
@smonroe4242 Please, go to https://cheatera.pp.ua/logout 
May be a bad response from Intra broke the session and clicking on the link  https://cheatera.pp.ua/logout  will help fix it

**Comment by smonroe4242** [comment]
This link also takes me to the same error.
Also, aside from myself, at least two other people have had this issue, all
at 42 Silicon Valley. Perhaps the error is specific to our region? Just a
thought.

**Comment by smonroe4242** [comment]
Also, when switching to between light/dark theme, error comes as `Forbidden (#403)
42API error! Please, try again`, then after following links resumes to `Error (#8)
An internal server error occurred.`

**Comment by smonroe4242** [comment]
When going to the top left https://cheatera.pp.ua link I get 
```
Welcome!
If you have a trouble with style - please use hard refresh on page(refresh page with shift), or delete all you cookies
```
with no further content on page, though no error is thrown.
