### ISSUE TITLE
BUG: Перестает работать кнопка RESET

### ISSUE THREAD

**Issue by akorchyn** [unitfactoryAlumni/cheatera.pp.ua#138]
| OS : MacOS |
| Browser : (Safari, Chrome) |
| Theme | Dark/White/Both | Both
| У вас получилось повторить баг? | да

Шаги для повторения бага
1. Открыть калькулятор опыта.
2. Тыкать до получения ошибки, что максимально возможный уровень 30.
3. Кнопка ресет больше не работает

**Comment by setnemo** [comment]
undefined behavior
