### ISSUE TITLE
BUG: студенты чужих кампусов в таблицах на страницах проектов

### ISSUE THREAD

**Issue by Hoommus** [unitfactoryAlumni/cheatera.pp.ua#140]
| Вопрос | Ответ |
| ------------ | ------------ |
| OS | Ubuntu 18.04 |
| Browser | Google Chrome 75 |
| Theme | Both |
| У вас получилось повторить баг? | да |

Шаги для повторения бага
1. Открыть страницу любого непопулярного проекта: например, [libftasm](https://cheatera.pp.ua/students/projects/libftasm) или [In the Shadows](https://cheatera.pp.ua/students/projects/in-the-shadows)
2. Наблюдать за колонкой Location. Если значение `not set`, то это, скорее всего, студент не нашего кампуса.
3. И даже если значение нормальное, то это всё равно может быть не наш студент.
4. Перед вами баг.

**Comment by setnemo** [comment]
Баг известен примерно три месяца, это появилось после того, как @Millon15 накатил #66
