### ISSUE TITLE
FEATURE: улучшить calculator

### ISSUE THREAD

**Issue by ed-amielin** [unitfactoryAlumni/cheatera.pp.ua#143]
Улучшить calculator для выбора не сложности проекта (t1-t7), так как сейчас уже в интре невозможно увидеть какой сложности проект, а только показывается количество "XP", - а как следствие - поставте выбор на кнопках сколько "XP" должен дать проект и оставьте поле для ввода на какую оценку его планируется сделать.
| Вопрос | Ответ |
| ------------ | ------------ |
| Что нужно добавить? | В calculator вместо кнопок выбора сложности проекта (t1-t7) ползунок с количеством "XP" указаных в проекте в интре |
| Как это должно работать? | Пользователь выбирает ползунком количество "XP" указаных в проекте в интре для данного проекта |
| Как это не должно работать | Кнопки со сложностью проекта (t1-t7) невозможно использовать так как я не знаю какой сложности был проект - я вижу в интре теперь только количество "XP" |
| Какую проблему поможет решить эта фича? | Будет возможность корректно посчитать свой предполагаемый рейтинг |

**Comment by setnemo** [comment]
бегунок это антиюзерфрендли штука имхо. Количество хр соотвествуют старым данным? Можно оставить кнопки но вписать в них новые названия. Или добавить еще одно поле ввода @Millon15 что думаешь?

**Comment by ed-amielin** [comment]
В том то и дело, что я не знаю как новые данные по "XP" соотносятся со старыми данными по сложности проекта - раньше было указано только сложность проекта (от t1 до t7), а сейчас от 25XP (за Curriculum Vitae или Piscine Reloaded) до 1000 (за First Internship) и 1500XP (за Final Internship)

**Comment by Millon15** [comment]
@omentes я пока хз, посмотрю на неделе, подумаю, на выходных может пофикшу!

**Comment by olehsamoilenko** [comment]
Насколько я понял, нам действительно несложная математика: 100хр соответсвует т1, 225хр - т2, 375хр - т3 и т.д.
Поэтому действительно можно поменять текст на кнопках и будет 👌🏿

**Comment by Millon15** [comment]
Fixed by #146

**Comment by Millon15** [comment]
@omentes Можешь ревьювить и мёрджить все мои сегодняшнее pull-requests и клонить мастер на сервере!
