### ISSUE TITLE
Изменить шаблоны документации, создания нового ишью, пулреквеста

### ISSUE THREAD

**Issue by setnemo** [unitfactoryAlumni/cheatera.pp.ua#24]
**Is your feature request related to a problem? Please describe.**
Нужно улучшить и дополнить документацию, перевести и написать валидные шаблоны для issue, pull request, etc

Документация находится в папке .github

**Comment by Millon15** [comment]
Что ты имеешь ввиду под дополнить документацию, можешь пояснить пожалуйста?

**Comment by setnemo** [comment]
> Что ты имеешь ввиду под дополнить документацию, можешь пояснить пожалуйста?

ну сейчас шаблоны не очень корректные. Те, которые юзаются при создании нового ишью и тд. Посмотри темплейты в репе
