### ISSUE TITLE
Поправить авторизацию

### ISSUE THREAD

**Issue by setnemo** [unitfactoryAlumni/cheatera.pp.ua#42]
1. Добавить редирект не на авторизацию по логину, а сразу по ссылке интры
2. Добавить сохранения урла входа (если был редирект на авторизацию), и со страницы welcome  сразу отправлять туда, откуда отправило на авторизацию

**Результатом выполнения двух пунктов будет следующее поведение**
При попытке входа на скрытую страницу автоматически идет авторизация в интре и возвращает на страницу, которую открыли без авторизации

**Comment by Hoommus** [comment]
Не умею писать ишью, следовательно пишу куда попало, если тема касается.

Стоит ещё исправить отображение сообщения об ошибке в форме авторизации - когда кликаешь на кнопку "Auth with 42" - в этот момент запускается валидация (?) всей формы и она ругается на отсутствие текста в поле "Username":

<img width="627" alt="screen shot 2019-03-08 at 8 25 36 pm" src="https://user-images.githubusercontent.com/19969908/54047861-e4494e80-41e0-11e9-8179-1dbfa7eae8fc.png">

**Comment by setnemo** [comment]
там не должно быть этой кнопки, на ссылку по 42 есть ссылка в меню
