### ISSUE TITLE
Final mark resets to max after calculation in experience calculator 

### ISSUE THREAD

**Issue by maksmaers** [unitfactoryAlumni/cheatera.pp.ua#44]
**Describe the bug**
Final mark resets to max after calculation in experience calculator 

**To Reproduce**
1. Go to http://beta.cheatera.pp.ua/calculator
2. Set level tier T3
2. Set final mark to minimal value (50 for example) 
3. Click "Calculate"
4. After  final mark field resets to 125

**Expected behavior**
 final mark field stays 50

Desktop

**Comment by setnemo** [comment]
@Millon15

**Comment by setnemo** [comment]
@maksmaers thanks for testing
