### ISSUE TITLE
Wrong experience calculator behavior with max level

### ISSUE THREAD

**Issue by maksmaers** [unitfactoryAlumni/cheatera.pp.ua#45]
**Describe the bug**
Wrong experience calculator behavior with max level

**To Reproduce**
1. Go to http://beta.cheatera.pp.ua/calculator
2. Set current level 29.99
3. Set tier level T3
3. Set finalmark 125
4. Click "Calculate"
5. Result: 29.988476349271

**Expected behavior**
expected correct result

Desktop

**Comment by setnemo** [comment]
@Millon15

**Comment by setnemo** [comment]
@maksmaers thanks for testing
