### ISSUE TITLE
No server data validation for experience calculator

### ISSUE THREAD

**Issue by maksmaers** [unitfactoryAlumni/cheatera.pp.ua#46]
**Describe the bug**
A clear and concise No server data validation for experience calculator of what the bug is.

**To Reproduce**
1. GO http://beta.cheatera.pp.ua/calculator
2. Open HTML inspector 
3. Change value for tier field 
4. Click Calculate 
5. Page go down 

**Expected behavior**
Add server valuation data 

![download](https://user-images.githubusercontent.com/1178783/54071358-35eee900-4274-11e9-9e85-f950ee453c9e.png)

**Comment by setnemo** [comment]
@Millon15

**Comment by setnemo** [comment]
@maksmaers thanks for testing
