### ISSUE TITLE
Предоставить доступ телеграм боту к расчетам калькулятора опыта

### ISSUE THREAD

**Issue by denysovvl** [unitfactoryAlumni/cheatera.pp.ua#63]
CALCULATOR
POST
REQUEST
понимаешь? (это не сложно)

**Comment by setnemo** [comment]
@Millon15 
Требуется скачать и установить постмен. Постменом будешь тестить. Нужно передавать постом запрос, в теле которого будет тиер, лвлстарт, финалмарк. Респонс - echo $result

Сделать отдельным роутом, где разрешены пост запросы извне (ok, google, CSRF yii2)
