### ISSUE TITLE
Добавить друзей 

### ISSUE THREAD

**Issue by setnemo** [unitfactoryAlumni/cheatera.pp.ua#65]
Взять за основу табличку, которая уже есть со старых читеров 
По сути там только избранные, и нет двухсторонний связи.
Реализовать добавление и подтверждение друзей, отписку, страницу друзей 
Добавить таблицу событий, куда будем писать лог событий. 
Добавить иконку в меню, если есть заявки в друзья.
Добавить возможность убрать эту иконку

**Comment by Millon15** [comment]
Issue migrated to cheatera-pp-ua/cheatera.pp.ua#13
