### ISSUE TITLE
Тёмная тема

### ISSUE THREAD

**Issue by akoropet** [unitfactoryAlumni/cheatera.pp.ua#79]
При переходе на все ссылки через меню "Students" и при переходе в "Profile" исчезает тёмная тема.

**Comment by setnemo** [comment]
Это возможно только если нет доступа к кукам. Темная тема использует куки. Если они не заблочены - все работает нормально, воспроизвести не удалось

**Comment by akoropet** [comment]
Проблема наблюдается при выборе английской версии сайта.

**Comment by setnemo** [comment]
Какой браузер?

**Comment by akoropet** [comment]
Safari

**Comment by setnemo** [comment]
https://support.apple.com/en-ca/guide/safari/sfri11471/11.0/mac/10.13

Попробуй настроить сохранение куков, или проверить, сохраняются ли они

**Comment by setnemo** [comment]
@akoropet расскажешь, получилось ли. Интересно

**Comment by akoropet** [comment]
Блокировака куков была отключена, но в списке сайтов от кого принимались куки ресурса cheatera.pp.ua не было. Я просто заблокировал, попробовал, обратно убрал блокировку и всё заработало.

**Comment by setnemo** [comment]
> Блокировака куков была отключена, но в списке сайтов от кого принимались куки ресурса cheatera.pp.ua не было. Я просто заблокировал, попробовал, обратно убрал блокировку и всё заработало.

спасибо!
