### ISSUE TITLE
Текст при тёмной теме

### ISSUE THREAD

**Issue by akoropet** [unitfactoryAlumni/cheatera.pp.ua#81]
В "Services->Corrections" было бы неплохо сделать более ярким цветом подписи осей.

**Comment by setnemo** [comment]
Для того, кто будет править
Документация по chart js https://www.chartjs.org/docs/latest/configuration/legend.html

**Comment by Millon15** [comment]
Issue migrated to cheatera-pp-ua/cheatera.pp.ua#5

**Comment by Millon15** [comment]
Это не баг, а фича, текст меньше бросается в глаза!
