### ISSUE TITLE
Dark mode framing of student list

### ISSUE THREAD

**Issue by tpokalch** [unitfactoryAlumni/cheatera.pp.ua#83]
the "show profile picture" icon of "online" students is half framed by black lines in dark mode

**Comment by setnemo** [comment]
Need overwrite
`table > thead > tr > th, .table > thead > tr > th, table > tbody > tr > th, .table > tbody > tr > th, table > tfoot > tr > th, .table > tfoot > tr > th, table > thead > tr > td, .table > thead > tr > td, table > tbody > tr > td, .table > tbody > tr > td, table > tfoot > tr > td, .table > tfoot > tr > td {
    border-color: transparent; 
}`
/assets/f4f33c32/superhero/bootstrap.css:6839

**Comment by Millon15** [comment]
Got it!

**Comment by Millon15** [comment]
Issue migrated to cheatera-pp-ua/cheatera.pp.ua#1
